# Generated by Django 3.1.7 on 2021-04-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('title', models.CharField(max_length=30)),
                ('msg', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
    ]
